INSERT INTO ACCOUNT (NAME, PASSWORD) VALUES ('Scott', 'test');
INSERT INTO ACCOUNT (NAME) VALUES ('JackWilliam');
INSERT INTO ACCOUNT (NAME) VALUES ('Rose');
INSERT INTO ACCOUNT (NAME) VALUES ('SomeName');
INSERT INTO ACCOUNT (NAME) VALUES ('Tester');